CREATE TABLE public.mock_data (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_first_name VARCHAR(50) NULL,
    customer_last_name VARCHAR(50) NULL,
    customer_age INT NULL,
    customer_email VARCHAR(50) NULL,
    customer_country VARCHAR(50) NULL,
    customer_postal_code VARCHAR(50) NULL,
    customer_pet_type VARCHAR(50) NULL,
    customer_pet_name VARCHAR(50) NULL,
    customer_pet_breed VARCHAR(50) NULL,
    seller_first_name VARCHAR(50) NULL,
    seller_last_name VARCHAR(50) NULL,
    seller_email VARCHAR(50) NULL,
    seller_country VARCHAR(50) NULL,
    seller_postal_code VARCHAR(50) NULL,
    product_name VARCHAR(50) NULL,
    product_category VARCHAR(50) NULL,
    product_price NUMERIC(10, 2) NULL,
    product_quantity INT NULL,
    sale_date VARCHAR(50) NULL,
    sale_customer_id INT NULL,
    sale_seller_id INT NULL,
    sale_product_id INT NULL,
    sale_quantity INT NULL,
    sale_total_price NUMERIC(10, 2) NULL,
    store_name VARCHAR(50) NULL,
    store_location VARCHAR(50) NULL,
    store_city VARCHAR(50) NULL,
    store_state VARCHAR(50) NULL,
    store_country VARCHAR(50) NULL,
    store_phone VARCHAR(50) NULL,
    store_email VARCHAR(50) NULL,
    pet_category VARCHAR(50) NULL,
    product_weight REAL NULL,
    product_color VARCHAR(50) NULL,
    product_size VARCHAR(50) NULL,
    product_brand VARCHAR(50) NULL,
    product_material VARCHAR(50) NULL,
    product_description TEXT NULL,
    product_rating REAL NULL,
    product_reviews INT NULL,
    product_release_date VARCHAR(50) NULL,
    product_expiry_date VARCHAR(50) NULL,
    supplier_name VARCHAR(50) NULL,
    supplier_contact VARCHAR(50) NULL,
    supplier_email VARCHAR(50) NULL,
    supplier_phone VARCHAR(50) NULL,
    supplier_address VARCHAR(50) NULL,
    supplier_city VARCHAR(50) NULL,
    supplier_country VARCHAR(50) NULL
)